config/routes.rb
Rails.application.routes.draw do
  
 root 'pages#home'
 get 'home' , to: 'pages#home'
 
 #get 'recipes', to: 'recipes#index'
 #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
 #post 'recipes', to: 'recipes#create'
 #get 'recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
 #patch 'recipes/:id', to: 'recipes#update'
 #get 'recipes/:id', to: 'recipes#show', as: 'recipe'
 #delete 'recipes/:id', to: 'recipes#destroy'
 
 resources :recipes

end

app/models/cheff.rb
class Cheff < ActiveRecord::Base
 has_many :recipes
 before_save {self.email = email.downcase}
  validates :name, presence: true, length: {minimum: 5, maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 55},
                                    uniqueness: {case_sensitive: false},
                                    format: {with: VALID_EMAIL_REGEX}
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :cheff
  validates :cheff_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 20}
  validates :summery, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def show
    @recipe = Recipe.find(params[:id])
    # binding.pry
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(cheff, options = {size:80})
    gravatar_id = Digest::MD5::hexdigest(cheff.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: cheff.name, class: 'gravatar')
    
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; MyRecipies TA Raza 2015</p>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    
    <%= link_to "MyRecipies", root_path, class: "btn btn-lg btn-success", id:"logo"%>
    
    <div class = "nav_item">
      <%= link_to "Link 1", "", class:"btn btn-default btn warning" %>
    </div>
    
    <div class = "nav_item">
      <%= link_to "Link 2", "", class:"btn btn-default btn warning" %>
    </div>
    
    <div class = "nav_item">
      <%= link_to "Link 3", "", class:"btn btn-default btn warning" %>
    </div>
    
    
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

        <%= render 'layouts/navigation' %>
 
      <div class= "container">
        <%= yield %>

        <%= render 'layouts/footer' %>
      </div>
      
</body>
</html>

app/views/pages/home.html.erb
<div class= "center jumbotron">
  
  <h1>Welcome To MyRecipies App </h1>
  <h2>This is the home page for the tastiest recipies of the world! </h2>
  
  <%= link_to "Sign up now!", "", class: "btn btn-lg btn-success"%>
</div>

<div class= "row">
  <div class= "col-lg-4">
    <div class= "midrow">
      <h3>View Recipies as a GUEST user</h3>
      <h2 class="left">Browse and view recipies as a guest user and Sign up later</h2>
      <p><%= link_to "View Recipies",recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
  </div>
  
  <div class= "col-lg-4">
    <div class= "midrow">
      <h3>View Recipies as a GUEST user</h3>
      <h2 class="left">Browse and view recipies as a guest user and Sign up later</h2>
      <p><%= link_to "View Recipies",recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
  </div>
  
  <div class= "col-lg-4">
    <div class= "midrow">
      <h3>View Recipies as a GUEST user</h3>
      <h2 class="left">Browse and view recipies as a guest user and Sign up later</h2>
      <p><%= link_to "View Recipies",recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<hr/>
<% @recipes.each do |recipe| %>
  <div class = "row">
    <div class = "col-md-2">
      <section class="cheff_info center">
        <%= gravatar_for recipe.cheff, size: 100 %>
        <h5>Posted By <%= recipe.cheff.name %></h5>
        
      </section>
    </div>
    <div class="col-lg-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %> </h4>
      <p><%= recipe.summery %></p>
      <p>
        <span class= 'quiet'><small><%= time_ago_in_words(recipe.created_at) %></small></span>
      </p>

    </div>
  </div>
 <hr/>
<% end %>

app/views/recipes/show.html.erb
<p>
  <h1> <%= @recipe.name %> </h1>
</p>
  
  <div class = 'row'>
    
    <div class = 'col-md-4 pull-right center'>
      <%= gravatar_for @recipe.cheff, size: 100 %>
      <p>
        <h5>Brought to you by: <%= @recipe.cheff.name %></h5>
      </p>
    </div>
   
    <div class ='col-md-8'>
      <h3> <%= @recipe.summery %> </h3>
        <div class = 'well'>
          <p>
            <strong>Cooking Method:</strong>
          </p>
            <%= @recipe.description %>
        </div>
    </div>

  </div> <%# Row Div %>
  
  <h5><%= link_to 'Return to recipes:', recipes_path, class: 'btn btn-warning btn-small' %></h5>